#!/bin/sh
mkdir -p /var/lib/pykmapd
install -m 0755 pykmapd /var/lib/pykmapd
install -m 0644 pykmapd@.service /usr/lib/systemd/system/pykmapd@.service
install -m 0644 99-pykmapd.rules /usr/lib/udev/rules.d/99-pykmapd.rules
