#!/usr/bin/env python
# vim: ts=4 sw=4 noet syntax=python:
import evdev
import asyncio
import sys
import signal
import traceback
import os

def cmd(foo):
	foo=str(foo)
	print(foo)
	os.system(foo)

def exexit(code=255):
	try:
		maploop.stop()
		extype,exinfo,extrbk=sys.exc_info()
		print("-KEYMAPPER-EXCEPTION-\n Excepton of type [%s]\n Details included [%s]\n-stack trace follows-\n%s"%(extype,exinfo,traceback.print_tb(extrbk)))
	finally:
		sys.exit(code)
def sigged(num,frm):
	maploop.stop()
	raise Exception("Invalid signal received, killing.")
	sys.exit(200)
def setmap():
	globals().update(evdev.ecodes.ecodes)
	mapping={}
	def kfunc(fnkey,*kfarg):
		if type(fnkey)==int:
			return fnkey
		else:
			return (lambda krd,val,key: fnkey(krd,val,key,*kfarg))
	def mapkey(key,normal,fn,*kfarg):
		mapping[key]={():kfunc(normal,*kfarg),(KEY_FN,):kfunc(fn,*kfarg)}
	def remap(key,out,*kfarg):
		mapping[key]={():kfunc(out,*kfarg)}
	def mapfn(key,fn,*kfarg):
		mapkey(key,key,fn,*kfarg)
	def setfn(key,*kfarg):
		mapkey(key,KEY_FN,KEY_FN,*kfarg)
	setfn(KEY_LEFTCTRL)
	remap(KEY_CAPSLOCK,KEY_LEFTCTRL)
#	mapfn(KEY_POWER,KEY_SYSRQ)
#	mapfn(KEY_UP,KEY_PAGEUP)
#	mapfn(KEY_DOWN,KEY_PAGEDOWN)
#	mapfn(KEY_LEFT,KEY_HOME)
#	mapfn(KEY_RIGHT,KEY_END)
#	mapfn(KEY_BACKSPACE,KEY_DELETE)
	mapfn(KEY_PAGEDOWN,brightness,-42)
	mapfn(KEY_PAGEUP,brightness,42)

	remap(KEY_VOLUMEDOWN,volume,-7)
	remap(KEY_VOLUMEUP,volume,7)
	remap(KEY_MUTE,volume,None)
#	mapfn(KEY_F6,decrease_brightness)
#	mapfn(KEY_F7,increase_brightness)
#	mapfn(KEY_F8,KEY_MUTE)
#	mapfn(KEY_F9,KEY_VOLUMEDOWN)
#	mapfn(KEY_F10,KEY_VOLUMEUP)
#	mapfn(KEY_RIGHTALT,KEY_COMPOSE)# still have to use -option compose:ralt b/c KEY_COMPOSE maps to menu by default.
#	mapfn(KEY_EQUAL,KEY_INSERT)
	return mapping

# vim: syntax=python ts=2 sw=2 noet
class Backlight:
    __targets={ "val":"/brightness",
            "max":"/max_brightness",
            "cur":"/actual_brightness" } 
    def __init__(self,path=""):
        self.__path=path
    def set(self,val):
        open(self.__path+self.__targets["val"],"w").write(str(max(min(val,self.max()),0)))
    def cur(self):
        return int(open(self.__path+self.__targets["cur"]).read())
    def max(self):
        return int(open(self.__path+self.__targets["max"]).read())
    def add(self,amt):
        self.set(self.cur()+amt)

backlight=Backlight("/sys/class/backlight/intel_backlight")

def keydown(kfn):
	return ( lambda krd,val,key,arg: (kfn(krd,val,key,arg) if val>0 else None ) )

@keydown
def increase_brightness(krd,val,key):
    backlight.add(42)

@keydown
def decrease_brightness(krd,val,key):
    backlight.add(-42)

@keydown
def brightness(krd,val,key,arg):
	backlight.add(arg)

@keydown
def volume(krd,val,key,arg):
	if arg is not None:
		cmd("pactl set-sink-volume @DEFAULT_SINK@ %+d%%"%(arg))
	else:
		cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle")

class KeyRemapperDevice:
	def __init__(self, readdev, mapping, grab=True):
		self._readdev = readdev
		if (grab):
			self._readdev.grab()
		self._mapping = mapping
		self._outputs = self._readdev.capabilities()
		self._outputs[EV_KEY] = evdev.ecodes.keys.keys() 
		del self._outputs[0]
		self._senddev = evdev.UInput (self._outputs, name=("s/"+self._readdev.name+"/.../g" ))
		self._keydown = set()
		asyncio.ensure_future(self.runloop())
	async def runloop(self):
		try:
			async for inputev in self._readdev.async_read_loop():
				if inputev.type == EV_KEY and self.has_key(inputev.code):
					self.set_key(self.map_key(inputev.code),inputev.value,inputev.code)
				else:
					self._senddev.write_event(inputev)
					self._senddev.syn()
		except:
			exexit(32)
	def has_key(self,key):
		return key in self._mapping.keys()
	def set_key(self,key,value,code):
		if (value==0):
			map(lambda keycode: keyself._keydown.discard(keycode) if type(keycode)==int else None,self._mapping[code].values())
		if type(key)==int:
			if value:
				self._keydown.add(key)
			else:
				self._keydown.discard(key)
			self._senddev.write(EV_KEY,key,value)
			self._senddev.syn()
		else:
			key(self,value,code)
	def map_key(self,inkey):
		posmaps=[(mapwhen,remapto) for mapwhen,remapto in self._mapping.get(inkey,{}).items() if set(mapwhen)<=self._keydown]
		posmaps.sort(key=lambda item:len(item[0]),reverse=True)
		return posmaps[0][1]

def main():
	mapping = setmap()
	dev = evdev.InputDevice('/dev/input/'+sys.argv[1])
	if dev.name[0:2]=='s/' and dev.name[-6:]=='/.../g':
		return 0
	mapper = KeyRemapperDevice(dev,mapping)
	global maploop
	maploop = asyncio.get_event_loop()
	maploop.run_forever()


if (__name__ == '__main__'):
	print(sys.argv[1],file=sys.stderr)
	signal.signal(signal.SIGTSTP,sigged)
	main()
